// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykwocflxfhjoabjzjvob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlrd29jZmx4Zmhqb2Fianpqdm9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MTExMDgsImV4cCI6MjA2ODI4NzEwOH0.WDn7r310l0jrVc8xGEdIVw9RNKgsTjNhlVJsqgRx9t8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});